"""Build the assignment report PDF from the included reproducible results."""
from pathlib import Path
import json
import csv
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image, KeepTogether

ROOT=Path(__file__).resolve().parent
OUT=ROOT/'Module6_Report.pdf'
res=json.loads((ROOT/'outputs'/'sfm_summary.json').read_text())
video_res=json.loads((ROOT/'outputs'/'video_analysis_summary.json').read_text())
with (ROOT/'outputs'/'camera_centres.csv').open() as stream:
    camera_rows=list(csv.DictReader(stream))
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='CoverTitle',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=24,leading=29,textColor=colors.HexColor('#17324D'),spaceAfter=12,alignment=TA_CENTER))
styles.add(ParagraphStyle(name='Deck',parent=styles['Normal'],fontSize=11,leading=16,textColor=colors.HexColor('#526477'),alignment=TA_CENTER,spaceAfter=12))
styles.add(ParagraphStyle(name='H1x',parent=styles['Heading1'],fontSize=16,leading=20,textColor=colors.HexColor('#17324D'),spaceBefore=8,spaceAfter=7))
styles.add(ParagraphStyle(name='H2x',parent=styles['Heading2'],fontSize=11.5,leading=14,textColor=colors.HexColor('#087E8B'),spaceBefore=6,spaceAfter=4))
styles.add(ParagraphStyle(name='Bodyx',parent=styles['BodyText'],fontSize=9.3,leading=13,spaceAfter=6))
styles.add(ParagraphStyle(name='Smallx',parent=styles['BodyText'],fontSize=8,leading=10,textColor=colors.HexColor('#526477'),spaceAfter=4))
styles.add(ParagraphStyle(name='TableHead',parent=styles['BodyText'],fontSize=8,leading=10,textColor=colors.white,fontName='Helvetica-Bold'))
styles.add(ParagraphStyle(name='Eq',parent=styles['BodyText'],fontName='Courier',fontSize=9.4,leading=14,leftIndent=12,backColor=colors.HexColor('#F0F5F7'),borderPadding=7,spaceBefore=3,spaceAfter=7))

def P(text,style='Bodyx'): return Paragraph(text,styles[style])
def footer(canvas,doc):
 canvas.saveState(); canvas.setStrokeColor(colors.HexColor('#D6E0E6'));canvas.line(.65*inch,.55*inch,7.85*inch,.55*inch)
 canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#607080'));canvas.drawString(.68*inch,.38*inch,'CSc 8830 | Module 6 | Motion and multi-view geometry')
 canvas.drawRightString(7.82*inch,.38*inch,f'{doc.page}');canvas.restoreState()

doc=SimpleDocTemplate(str(OUT),pagesize=letter,rightMargin=.68*inch,leftMargin=.68*inch,topMargin=.62*inch,bottomMargin=.72*inch,title='Module 6: Optical Flow, Tracking, and Structure from Motion',author='Sirichandana Bikkasani')
story=[]
story += [Spacer(1,.4*inch),P('Motion in Images','CoverTitle'),P('Optical flow, two-frame tracking, and four-view planar reconstruction','Deck'),P('CSc 8830 Computer Vision | Module 6 | Sirichandana Bikkasani','Deck'),Spacer(1,.2*inch)]
story += [P('Project question','H1x'),P('How can image motion be estimated between frames, checked at the pixel level, and combined across multiple viewpoints to recover scene structure? This project implements dense optical flow, local feature tracking, subpixel interpolation, and a calibrated planar multi-view reconstruction.','Bodyx')]
story += [P('Assignment goals and current evidence','H1x')]
status=[['Requirement','Evidence in this project'],['Two motion videos','35.83 s person unpacking/assembly clip and 45.05 s continuous road-traffic clip. Both are over 30 seconds and show visible motion.'],['Dense optical flow','Farneback flow was computed over the first 30 s of each clip and saved as a 30 s side-by-side MP4.'],['Two-frame tracking and pixel validation','80 features per clip were tracked; two approximate Frame B readings are compared with the predictions using endpoint error.'],['Four-view reconstruction','Completed using four included checkerboard images and prior phone calibration.']]
t=Table([[P(c,'TableHead') for c in status[0]]] + [[P(c,'Smallx') for c in row] for row in status[1:]],colWidths=[1.75*inch,5.0*inch],repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#17324D')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#CED8DE')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F4F7F9')]),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));story += [t,Spacer(1,8),P('<b>Input note:</b> Both clips are continuous recordings longer than 30 seconds. Each dense-flow output covers the first 30 seconds. The capture rate includes repeated frames, so the tracking check advances to the next distinct image when necessary.','Smallx'),PageBreak()]
story += [P('1. Optical flow and point tracking','H1x'),P('Brightness constancy assumes that a moving image point keeps approximately the same intensity over a small time interval. A first-order Taylor expansion produces the optical-flow constraint:','Bodyx'),P('I(x+u*dt, y+v*dt, t+dt) = I(x,y,t)<br/>Ix*u + Iy*v + It = 0','Eq'),P('This is one equation with two unknown velocity components, so a single pixel is insufficient. Lucas-Kanade assumes a small neighborhood shares one motion vector. For pixels i in that window, the equations form A d = b, with d = [u,v] and b = -It. The least-squares estimate minimizes squared error, and when transpose(A)*A is invertible, it is:','Bodyx'),P('d = inverse(transpose(A)*A) * transpose(A) * b','Eq'),P('The app detects Shi-Tomasi corners in frame t and uses pyramidal Lucas-Kanade to estimate their positions in the adjacent frame. A numbered side-by-side visualization and CSV expose (x0,y0), (x1,y1), displacement, and per-axis motion. The manual check compares a visually read location with the estimate using endpoint error = sqrt(square(xmanual-x1) + square(ymanual-y1)).','Bodyx'),P('Subpixel interpolation','H2x'),P('A tracked location is generally not at integer pixel coordinates. For (x0+a,y0+b), bilinear interpolation blends the four surrounding grayscale samples:','Bodyx'),P('I = (1-a)(1-b)I00 + a(1-b)I10 + (1-a)bI01 + a*b*I11','Eq'),P('Implementation and interpretation','H2x'),P('The dense field uses OpenCV Farneback flow and maps direction to hue and magnitude to brightness. The video is sampled at up to 10 frames per second and the app displays the original beside the flow field. Flow is an apparent image-motion estimate; camera movement, illumination change, blur, occlusion, and texture ambiguity can make it differ from physical object motion.','Bodyx'),PageBreak()]
story += [P('2. Four-view planar reconstruction','H1x'),P('The planar target is a 9 by 6 internal-corner checkerboard with 25 mm square spacing. Four images from the earlier phone-calibration exercise are included with this project. The previously estimated intrinsic matrix is K = [[3095.067,0,932.214],[0,3094.479,2024.674],[0,0,1]] for 1884 by 4080 images. The distortion coefficients are k1 = 0.069978, k2 = 0.921953, p1 = -0.004310, p2 = -0.002685, and k3 = -4.709119.','Bodyx'),P('For each view, the checkerboard grid provides 3D reference points Xi = (25c,25r,0) mm and detected image corners xi. OpenCV solvePnP estimates rotation Ri and translation ti under the calibrated camera model. The camera center in board coordinates is C = -transpose(R)*t. Adjacent views are undistorted, then corresponding corner rays are triangulated by minimizing their reprojection mismatch. Projection follows:','Bodyx'),P('x_image is proportional to K [R | t] X_world','Eq'),P('The known grid makes this a calibrated planar reconstruction with known geometry and metric scale. It is not unconstrained SfM of an unknown scene: pose estimation uses the known board dimensions. This controlled setup is appropriate for checking the multi-view geometry pipeline and its error.','Bodyx')]
img=ROOT/'outputs'/'four_view_reconstruction.png'
cam_table=[[P('View / image','TableHead'),P('X (mm)','TableHead'),P('Y (mm)','TableHead'),P('Z (mm)','TableHead')]]
for row in camera_rows:
    cam_table.append([P(f"{row['view']} / {row['image']}",'Smallx'),P(f"{float(row['camera_x_mm']):.1f}",'Smallx'),P(f"{float(row['camera_y_mm']):.1f}",'Smallx'),P(f"{float(row['camera_z_mm']):.1f}",'Smallx')])
ct=Table(cam_table,colWidths=[3.9*inch,.9*inch,.9*inch,.9*inch],repeatRows=1)
ct.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#087E8B')),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#CED8DE')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F4F7F9')]),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),3),('BOTTOMPADDING',(0,0),(-1,-1),3)]))
story += [Image(str(img),width=5.4*inch,height=3.4*inch),P('Figure 1. Triangulated checkerboard corners and four estimated camera centers; coordinates are in the checkerboard coordinate frame.','Smallx'),P('Estimated camera centers','H2x'),ct,PageBreak()]
story += [P('3. Results and validation','H1x')]
rows_data=[['Measure','Observed result'],['Calibration reprojection RMS',f"{res['calibration_reprojection_rms_px']:.3f} px (prior calibration result)"],['Detected / triangulated points',f"54 corners per view; {res['triangulated_points']} triangulated points across adjacent pairs"],['Points by adjacent pair','; '.join(f"{x['view_pair']}: {x['corners']}" for x in res['triangulated_point_count_per_adjacent_pair'])],['Known board extent','200 x 125 mm'],['Reconstructed extent',f"{res['boundary_extent_mm'][0]:.2f} x {res['boundary_extent_mm'][1]:.2f} mm"],['Extent difference',f"{res['extent_error_mm'][0]:+.2f} x {res['extent_error_mm'][1]:+.2f} mm"],['Depth spread of triangulated corners',f"{res['z_range_mm']:.2f} mm (ideal planar target: 0 mm)"]]
t=Table([[P(c,'TableHead') for c in rows_data[0]]]+[[P(c,'Smallx') for c in r] for r in rows_data[1:]],colWidths=[2.3*inch,4.45*inch],repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#087E8B')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#CED8DE')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F4F7F9')]),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));story += [t,Spacer(1,8),P('Interpretation','H2x'),P('The reconstructed width and height are close to the known checkerboard extent, with about 0.64 mm and 0.89 mm of extent difference. The 10.62 mm depth spread shows noticeable non-planarity in the triangulated estimates. Possible contributors include calibration residual, corner localization, small camera-baseline changes, and planar-scene geometry. The point-cloud extents can be checked directly: X extent = 200.365 - (-0.274) = 200.639 mm; Y extent = 125.739 - (-0.153) = 125.892 mm. Against the known 200 by 125 mm grid, the differences are +0.639 mm and +0.892 mm. The reported boundary is the point-cloud extent, not a direct hidden-object boundary detector.','Bodyx'),PageBreak()]
story += [P('4. Motion video results and tracking check','H1x')]
v1,v2=video_res['1'],video_res['2']
m1,m2=v1['manual_validation'],v2['manual_validation']
video_rows=[['Input','Duration; analyzed','Flow median*','LK tracks; median / max motion','Frame B: predicted / visual reference (px)','Endpoint error'],[f"Video 1: {v1['source_description']}",f"{v1['source_duration_seconds']:.2f} s; first 30 s",f"{v1['median_dense_flow_pixels_per_sample']:.3f}",f"{v1['tracked_points']}; {v1['median_track_displacement_pixels']:.3f} / {v1['maximum_track_displacement_pixels']:.2f}",f"Track {m1['track_id']}: ({m1['predicted_x1_px']:.2f},{m1['predicted_y1_px']:.2f}) / approx. ({m1['manual_reference_x1_px']:.0f},{m1['manual_reference_y1_px']:.0f})",f"{m1['endpoint_error_px']:.2f} px"],[f"Video 2: {v2['source_description']}",f"{v2['source_duration_seconds']:.2f} s; first 30 s",f"{v2['median_dense_flow_pixels_per_sample']:.3f}",f"{v2['tracked_points']}; {v2['median_track_displacement_pixels']:.3f} / {v2['maximum_track_displacement_pixels']:.2f}",f"Track {m2['track_id']}: ({m2['predicted_x1_px']:.2f},{m2['predicted_y1_px']:.2f}) / approx. ({m2['manual_reference_x1_px']:.0f},{m2['manual_reference_y1_px']:.0f})",f"{m2['endpoint_error_px']:.2f} px"]]
vt=Table([[P(c,'TableHead') for c in video_rows[0]]]+[[P(c,'Smallx') for c in r] for r in video_rows[1:]],colWidths=[1.03*inch,0.88*inch,0.63*inch,1.16*inch,2.20*inch,0.85*inch],repeatRows=1)
vt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#087E8B')),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#CED8DE')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F4F7F9')]),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
validation_text=(f"The Frame B reference locations were read approximately from enlarged images, not obtained from independent ground truth. Video 1 uses track {m1['track_id']} at {v1['tracking_pair_start_seconds']:.3f} to {v1['tracking_pair_end_seconds']:.3f} seconds: predicted ({m1['predicted_x1_px']:.2f}, {m1['predicted_y1_px']:.2f}) px versus visual reference about ({m1['manual_reference_x1_px']:.0f}, {m1['manual_reference_y1_px']:.0f}) px. Endpoint error = sqrt(({m1['manual_reference_x1_px']:.0f}-{m1['predicted_x1_px']:.2f})^2+({m1['manual_reference_y1_px']:.0f}-{m1['predicted_y1_px']:.2f})^2) = {m1['endpoint_error_px']:.2f} px. Video 2 uses track {m2['track_id']} at {v2['tracking_pair_start_seconds']:.3f} to {v2['tracking_pair_end_seconds']:.3f} seconds: predicted ({m2['predicted_x1_px']:.2f}, {m2['predicted_y1_px']:.2f}) px versus visual reference about ({m2['manual_reference_x1_px']:.0f}, {m2['manual_reference_y1_px']:.0f}) px, giving {m2['endpoint_error_px']:.2f} px endpoint error. Bilinear grayscale values at the tracked subpixel points are {v1['bilinear_gray_sample']:.1f} and {v2['bilinear_gray_sample']:.1f} on a 0-255 scale. These approximate visual checks should be described as estimates, not exact ground truth.")
interpretation_text=('The person clip shows localized hand and body motion against a mostly stationary room. The traffic clip shows moving vehicles against a largely stationary camera view. Dense-flow median is measured over the full image, so a large static background keeps it low even when a smaller region is moving. The 60 fps captures contain repeated images; the tracker skips a duplicate to compare the next distinct frame. Lucas-Kanade can still fail with blur, occlusion, low texture, or large motion. The four-view reconstruction uses a calibrated checkerboard with known geometry, rather than unconstrained reconstruction of an unknown scene.')
story += [vt,Spacer(1,5),P('*Median over all pixels; stationary background pixels are included.','Smallx'),P('Pixel-coordinate check','H2x'),P(validation_text,'Bodyx'),P('Interpretation','H2x'),P(interpretation_text,'Bodyx'),PageBreak()]
story += [P('Reproducibility and references','H1x'),P('The Streamlit application, source, four checkerboard images, calibration JSON, 3D point CSV, camera-center CSV, and reconstruction plot are in the Module6_OpticalFlow_SfM folder of the course GitHub repository. Use the README for setup. The analysis output can be recreated by running <font name="Courier">python -m src.create_sfm_outputs</font> from the project folder.','Bodyx'),P('Camera setup and submitted input images','H2x'),P('The included camera positions are estimated relative to the checkerboard plane from calibrated phone images. The camera intrinsics are reused from the Module 2 calibration; the included JSON records the image size, distortion coefficients, board grid, and calibration RMS. Four original viewpoint images are included under data/sfm_views/.','Bodyx'),P('References','H2x'),P('1. Szeliski, R. <i>Computer Vision: Algorithms and Applications</i>, 2nd ed. Optical flow, feature tracking, and multi-view geometry chapters. https://szeliski.org/Book/','Smallx'),P('2. OpenCV documentation. Optical Flow: Farneback and Pyramidal Lucas-Kanade methods. https://docs.opencv.org/4.x/d4/dee/tutorial_optical_flow.html','Smallx'),P('3. OpenCV documentation. Camera calibration, pose estimation, and 3D reconstruction functions: findChessboardCornersSB, solvePnP, undistortPoints, and triangulatePoints. https://docs.opencv.org/4.x/','Smallx'),P('4. Course reference playlist: Optical Flow | Structure from Motion | Object Tracking. https://www.youtube.com/playlist?list=PL2zRqk16wsdoYzrWStffqBAoUY8XdvatV','Smallx'),P('5. Previous camera calibration measurements and images produced for CSc 8830 Module 2; calibration reprojection RMS 0.722 px.','Smallx'),Spacer(1,8),P('<b>Repository:</b> https://github.com/siri423/CSc8830-Computer-Vision/tree/main/Module6_OpticalFlow_SfM','Smallx')]
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
